#!/bin/bash

source "redis-functions.sh"
for f in $(ls commands); do source "commands/$f"; done

# Settings
PORT=30000
TIMEOUT=2000
NODES=6
REPLICAS=1

# You may want to put the above config parameters into config.sh in order to
# override the defaults without modifying this script.

if [ -a config.sh ]
then
    source "config.sh"
fi

# Computed vars
ENDPORT=$((PORT+NODES))


if [ "$1" == "start" ]
then
    start_command
fi

if [ "$1" == "create" ]
then
    create_command
fi

if [ "$1" == "stop" ]
then
  stop_command
fi

if [ "$1" == "watch" ]
then
    watch_command
fi

if [ "$1" == "tail" ]
then
    tail_command
fi

if [ "$1" == "call" ]
then
    call_command
fi

if [ "$1" == "clean" ]
then
    clean_command
fi

if [ "$1" == "clean-logs" ]
then
    clean_logs_command
fi

echo "Usage: $0 [start|create|stop|watch|tail|clean]"
echo "start       -- Launch Redis Cluster instances."
echo "create      -- Create a cluster using redis-trib create."
echo "stop        -- Stop Redis Cluster instances."
echo "watch       -- Show CLUSTER NODES output (first 30 lines) of first node."
echo "tail <id>   -- Run tail -f of instance at base port + ID."
echo "clean       -- Remove all instances data, logs, configs."
echo "clean-logs  -- Remove just instances logs."
